//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wypozyczalnia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Samochody
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Samochody()
        {
            this.Wypozyczone = new HashSet<Wypozyczone>();
        }
    
        public int ID { get; set; }
        public int ID_KlasaPojazdu { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public string Generacja { get; set; }
        public short Rocznik { get; set; }
        public short MocKM { get; set; }
        public decimal CenaDoba { get; set; }
        public Nullable<decimal> CenaDlugoTerm { get; set; }
    
        public virtual KlasyPojazdow KlasyPojazdow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wypozyczone> Wypozyczone { get; set; }
    }
}
