//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wypozyczalnia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wypozyczone
    {
        public int ID { get; set; }
        public int ID_Samochod { get; set; }
        public int ID_Uzytkownik { get; set; }
        public System.DateTime DataOdbioru { get; set; }
        public System.DateTime DataZwrotu { get; set; }
    
        public virtual Samochody Samochody { get; set; }
        public virtual Uzytkownicy Uzytkownicy { get; set; }
    }
}
